defaults:
  - problem: prefix_sums
  - override hydra/job_logging: custom
  - _self_

hydra:
  run:
    dir: ./outputs/${name}/testing-${run_id}
  job_logging:
    handlers:
      file:
        filename: testing.log

name: testing_default

problem:
  model:
    test_iterations:
      low: 30
      high: 50
    model_path:

quick_test: False

prune:
  ifprune: False
  ratio: 10
  method: rand
  prune_bias: False
  prune_batchnorm: False